### PR TITLE
Update install info in README

### PR DESCRIPTION
**Pull request by timholy**
Things seem easier now, so I thought I'd try to streamline this. Of course, please correct anything here that's wrong.

There are lots of deprecation warnings (esp. for `Uint`), so perhaps several packages need tagging.

(And yes, I got my new laptop. Ubuntu 15.10 still has too many problems for me to switch over to this laptop for real work, but I thought I'd start playing with your repos.)

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Oh great :) The deprecations are all fixed on the branch `reactive_next`, but this branch has it's own problems at the moment (it needs either reactive next, or a version my version, which I currently use locally. Also GLAbstraction and GLWindow need to be on that branch).
There are a few lines of code which need to br commented in/out, depending on the reactive version you use. I just hope we figure out the problems with Reactive next and things can move forward from there!

**Comment by SimonDanisch** [comment]
I just testet it: the readme changes seem to be accurate :)

**Comment by timholy** [comment]
Just FYI, other than `Pkg.test("GLVisualize")` every example I've tried has failed so far. I can submit bug reports if you want, but presumably you know about them?

**Comment by SimonDanisch** [comment]
Quite likely ;) If `Pkg.test("GLVisualize")` works, it's already a very good sign (kind of unexpected :D )

**Comment by timholy** [comment]
Yep. I should say I'm in no hurry, plenty of other stuff to do.

**Pull request merged**
