### PR TITLE
Add volumetric (absorption) rendering of RGBA volumes

### PR DESCRIPTION
**Pull request by timholy**
This is a cartoon, but hopefully at least a starting point. ~~I'll add some comments.~~ (seems the in-code comments suffice)

### CODE REVIEW

**Comment by SimonDanisch** [comment]
>// how to declare this is an RGBA array?
Can't, which is why I was saying that it's a nice example for Transpiler: the julia code will track the element type and make things work :). Like this you just need to do: `texture(rgb_texture, uvw).xyz` instead of `.x`.

**Comment by timholy** [comment]
OK, this is weird: despite the fact that I've commented out all the code I added, except for a stub, I'm getting this:
```julia
OK, I'm getting
```julia
WARNING: shader /home/tim/.julia/v0.6/GLVisualize/src/../assets/shader/volume.frag didn't compile. 
0(15) : error C0000: syntax error, unexpected ';', expecting "::" at token ";"
ERROR: program 20 not linked. Error in: 
/home/tim/.julia/v0.6/GLVisualize/src/../assets/shader/fragment_output.frag or /home/tim/.julia/v0.6/GLVisualize/src/../assets/shader/util.vert or /home/tim/.julia/v0.6/GLVisualize/src/../assets/shader/volume.vert or /home/tim/.julia/v0.6/GLVisualize/src/../assets/shader/volume.frag
Fragment info
-------------
0(15) : error C0000: syntax error, unexpected ';', expecting "::" at token ";"
(0) : error C2003: incompatible options for link

Stacktrace:
 [1] compile_program(::Array{GLAbstraction.Shader,1}, ::Array{Tuple{Int64,String},1}) at /home/tim/.julia/v0.6/GLAbstraction/src/GLShader.jl:205
 [2] (::GLAbstraction.##76#82{Dict{Symbol,Any},NTuple{4,String}})() at /home/tim/.julia/v0.6/GLAbstraction/src/GLShader.jl:270
 [3] get!(::GLAbstraction.##76#82{Dict{Symbol,Any},NTuple{4,String}}, ::Dict{Any,GLAbstraction.GLProgram}, ::Tuple{NTuple{4,String},Array{Array{String,1},1}}) at ./dict.jl:449
 [4] gl_convert(::GLVisualize.GLVisualizeShader, ::Dict{Symbol,Any}) at /home/tim/.julia/v0.6/GLAbstraction/src/GLShader.jl:262
 [5] GLAbstraction.RenderObject(::Dict{Symbol,Any}, ::GLVisualize.GLVisualizeShader, ::GLVisualize.##37#39{GLVisualize.VolumePrerender}, ::Void, ::GeometryTypes.HyperRectangle{3,Float32}, ::Void) at /home/tim/.julia/v0.6/GLAbstraction/src/GLTypes.jl:309
 [6] assemble_robj(::Dict{Symbol,Any}, ::GLVisualize.GLVisualizeShader, ::GeometryTypes.HyperRectangle{3,Float32}, ::UInt32, ::GLVisualize.VolumePrerender, ::GLVisualize.##216#217) at /home/tim/.julia/v0.6/GLVisualize/src/utils.jl:36
 [7] assemble_shader(::Dict{Symbol,Any}) at /home/tim/.julia/v0.6/GLVisualize/src/utils.jl:63
 [8] visualize(::Any, ::GLAbstraction.Style{:absorption}, ::Dict{Symbol,Any}) at /home/tim/.julia/v0.6/GLVisualize/src/visualize_interface.jl:21
 [9] visualize(::Any, ::Symbol) at /home/tim/.julia/v0.6/GLVisualize/src/visualize_interface.jl:20
```
Any ideas? If you edit the shader file(s) and then call `visualize` again, does it use the new shaders? Any debugging tips? I'm not fresh on this stuff, sorry.

**Comment by timholy** [comment]
OK, I think I have this mostly figured out. My main concerns now have to do with coordinates and physics. Let's consider a case where the voxels aren't isotropic, and let's imagine that one axis is at 10x worse resolution than the other two (so this is a big, big deal). Then traversing a voxel along a "skinny" direction should (if we're modeling the physics correctly) cause a much smaller reduction in the integrated translucency than traversing the same voxel in the "fat" direction, because in the real world we've passed through very different amounts of "stuff" depending on the tracing direction. This seems to have several consequences:
- In the raytracing equation we need to compute a `stepsize_world`
- Per-voxel alpha needs to be quoted in units of opacity/length (where length = world length)
- If you specify the input as an AxisArray, and let's say you specify the axis information in microns. Should alpha be opacity/micron? Or opacity/scaledps, where `scaledps = ps ./ maximum(ps)`? It's interesting to think about the consequences of supplying the "same" image at two different resolutions (like in an image pyramid), say one version of dimensions `m`-by-`n`-by-`p` with pixel spacing `Δx`-by-`Δy`-by-`Δz`, and the other at size `m/2`-by-`n/2`-by-`p/2` with pixel spacing `2Δx`-by-`2Δy`-by-`2Δz`. How should the alpha channel data scale with the resolution?

So I'm checking in to see if you follow a particular standard/reference/philosophy with regards to these issues, or whether there hasn't been a lot of attention paid to this yet in the volume imaging and if you'd appreciate someone coming in and thinking it through for you.

**Comment by timholy** [comment]
Sorry to keep bombarding you. I've added an indexed variant now, where it looks up the color assigned to each voxel in a table. This can be used for labeling different structures in a 3d volume. Unfortunately, as far as I can tell the array access to get the `index` always returns 0. Demo:
```julia
julia> using GLVisualize, IndirectArrays, Colors

julia> T = RGBA{Float32}
ColorTypes.RGBA{Float32}

julia> volumedata = IndirectArray(fill(Int32(2), 10, 10, 10), [T(1,0,0,1), T(0,1,0,1), T(0,0,1,1)]);

julia> window = glscreen();

julia> volume = visualize(volumedata, :absorption)
GLAbstraction.Context{GLAbstraction.DeviceUnit}(GLAbstraction.Composable[RenderObject with ID: 4
], 49: "map(map(input-23), input-27, input-28, input-26)" = GeometryTypes.HyperRectangle{3,Float32}(Float32[0.0, 0.0, 0.0], Float32[1.0, 1.0, 1.0]) GeometryTypes.HyperRectangle{3,Float32} , 47: "input-27" = Float32[1.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0; 0.0 0.0 1.0 0.0; 0.0 0.0 0.0 1.0] StaticArrays.SArray{Tuple{4,4},Float32,2,16} )

julia> _view(volume, window)

julia> renderloop(window)
```
You see a relatively transparent red cube. However, it should be either a green cube (1-based indexing) or a blue cube (0-based indexing).

**Comment by SimonDanisch** [comment]
I didn't use a template for `volume_data` since I was only using one type. But for the int32 indexed volume it must actually be an isampler. I'll push a fix!

**Comment by SimonDanisch** [comment]
>If you edit the shader file(s) and then call visualize again, does it use the new shaders?  

I forgot the exact rules under which I cache shaders. But I think if it errors the next one will get used.
I'd just use `GLAbstraction.empty_shader_cache!()` when developing interactively!

**Comment by timholy** [comment]
Another question: does `texture` interpolate? That doesn't entirely make sense for an index label.

**Comment by SimonDanisch** [comment]
For integer textures I default to not interpolating. See:
https://github.com/JuliaGL/GLAbstraction.jl/blob/master/src/GLTexture.jl#L456

So whether it interpolates or not is a parameter of the texture. Although I remember integer textures not working with linear interpolation - can't really find the relevant section in the OpenGL documentation right now, though :(

**Comment by SimonDanisch** [comment]
>or whether there hasn't been a lot of attention paid to this yet in the volume imaging and if you'd appreciate someone coming in and thinking it through for you.

I'd be very happy :)

**Comment by timholy** [comment]
OK, we'll see if this passes tests. Meanwhile, if you want some fun, clone the brand-new https://github.com/timholy/AllenBrain.jl and run `Pkg.build` on it. Then download the 50um resolution dataset from http://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/annotation/ccf_2016/. Finally, in the directory you stored it, try this:
```julia
using AllenBrain

if !isdefined(Main, :vertexlist)
    global g, vertexlist, aob, baot, mea, aaa, pmco, bstp
    g, vertexlist = ontology("mouse")
    const aob  = structureids(r"AOB", vertexlist)
    const baot = structureids(r"BA$", vertexlist)
    const mea  = structureids(r"MEA", vertexlist)
    const aaa  = structureids(r"AAA", vertexlist)
    const pmco = structureids(r"COApm", vertexlist)
    const bst  = structureids(r"BST", vertexlist)
end

using FileIO, AxisArrays, Unitful, Colors
using Unitful: μm

ano = load("annotation_50.nrrd")
ano = AxisArray(ano.data, (:P, :I, :R), (50μm, 50μm, 50μm))

volumedata = colorize!(ano, RGBA(1,1,1,0.2),
                       aob=>RGBA(5.0,0,0,10.0),
                       bst=>RGBA(0,5.0,0,10.0),
                       pmco=>RGBA(2.0,0,5.0,10.0),
                       mea=>RGBA(1,0,5.0,10.0),
                       union(baot,aaa)=>RGBA(0,0,4.0,10.0))

nothing
```
My favorite new way to explore brain anatomy :smile:.

**Comment by SimonDanisch** [comment]
image
Nice :)

**Comment by timholy** [comment]
OK, now with examples too. I noticed none of the volumetric rendering is tested automatically, so I didn't add these to the tests. Let me know if you want me to change that.

From my perspective this is good to go.

**Comment by SimonDanisch** [comment]
Great! Thanks a lot :)

**Comment by Evizero** [comment]
oh, this looks interesting

**Comment by timholy** [comment]
Yeah, it's pretty fun. Keep in mind that currently the absorption model isn't scaled to voxels, so I've done "weird" stuff like assign voxels a color `RGBA(10.0,6.0,0.0,3.0)` to get the rendering right. I plan on changing the scaling someday (no idea when, other projects seem more pressing right now), so if you do play with it keep in mind that your scripts might break sometime in the future. But it should be just a scale factor, so hopefully not too bad to fix.

**Comment by Evizero** [comment]
Its an interesting feature to experiment with.

out2

**Comment by timholy** [comment]
Oh, thanks for teaching me about byzanz. Here's a moving version of a figure I just put together for a review article I'm writing:
brain

**Comment by Evizero** [comment]
Wow, this is really cool. I have been looking for a good way to visualize an acoustic field. I just need to capitalize on whatever magic color intensity logic you have there (I'll figure that part out).

**Comment by timholy** [comment]
It's just the [Beer-Lambert law](https://en.wikipedia.org/wiki/Beer%E2%80%93Lambert_law), but we need to think about the proper units to express these coefficients and how to modify the raytracing when voxels happen to be anisotropic in physical space.

**Pull request merged**
