### PR TITLE
next features

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by hustf** [comment]
11000 changes. I will check this out  - julia needs windows graphics.

**Comment by SimonDanisch** [comment]
I'm actually just about to merge most of these into master and tag it! Hopefully done today! Some need to wait a bit for my next refactor, though ;) Hope it'll be a quick one!

**Comment by hustf** [comment]
Even better. Will wait the. And a tag!

**Comment by SimonDanisch** [comment]
see #105 ;) This was actually just for getting an overview!

**Comment by vchuravy** [comment]
That's a lot of change :)

**Comment by tbreloff** [comment]
Simon is like me... The best time for a refactor is right before the code
is stable and ready for release. :)

**Pull request closed without merging**
