### PR TITLE
Add missing vertex shader

### PR DESCRIPTION
**Pull request by timholy**
This gets the "particles/particles.jl" demo working for me.

Does `particles/cubicles.jl` work for you? I get
```jl
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{GLAbstraction.PerspectiveCamera{T}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,Float32}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,Float32}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,Float32}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,Float32}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,Float32}}, ::Reactive.Signal{GeometryTypes.SimpleRectangle{Int64}}, ::Reactive.Signal{Float32}, ::Reactive.Signal{Float32}, ::Reactive.Signal{Float32}, ::Reactive.Signal{GLAbstraction.Projection})
This may have arisen from a call to the constructor GLAbstraction.PerspectiveCamera{T}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  GLAbstraction.PerspectiveCamera{T<:Real}(::Reactive.Signal{GeometryTypes.SimpleRectangle{Int64}}, ::Union{FixedSizeArrays.Vec{3,T<:Real},Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}}, ::Union{FixedSizeArrays.Vec{3,T<:Real},Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}, ::Reactive.Signal{T<:Real}, ::Reactive.Signal{T<:Real}, ::Reactive.Signal{T<:Real}, ::Any, ::Any)
  GLAbstraction.PerspectiveCamera{T<:Real}(::Reactive.Signal{GeometryTypes.SimpleRectangle{Int64}}, ::Union{FixedSizeArrays.Vec{3,T<:Real},Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}}, ::Union{FixedSizeArrays.Vec{3,T<:Real},Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}, ::Reactive.Signal{T<:Real}, ::Reactive.Signal{T<:Real}, ::Reactive.Signal{T<:Real}, ::Any, ::Any, ::Any)
  GLAbstraction.PerspectiveCamera{T<:Real}(::Reactive.Signal{GeometryTypes.SimpleRectangle{Int64}}, ::Union{FixedSizeArrays.Vec{3,T<:Real},Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}}, ::Union{FixedSizeArrays.Vec{3,T<:Real},Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}, ::Reactive.Signal{FixedSizeArrays.Vec{3,T<:Real}}, ::Reactive.Signal{T<:Real}, ::Reactive.Signal{T<:Real}, ::Reactive.Signal{T<:Real}, ::Any, ::Any, ::Any, ::Any)
  ...
 in call at essentials.jl:57
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
while loading /home/temp/.julia/v0.4/GLVisualize/examples/particles/cubicles.jl, in expression starting on line 40
```
(The red coloration I see when I run this locally suggests it's a `Reactive.Signal` type problem.)

Relatedly, I'm just teaching myself OpenGL. Your recent work on the examples is enormously helpful. I'm also going through http://www.opengl-tutorial.org/beginners-tutorials and trying to replicate them in GLVisualize. On the tutorial 2, here are my notes-in-progress, which highlight some unexpected behavior:

## Grayscale triangle

	using GLVisualize, GeometryTypes
	
    # Construct a triangle in terms of vertices & faces
    ## Provide the (x,y,z) location of each vertex
	v = Point3f0[(-1, -1, 0), (1, -1, 0), (0, 1, 0)]

Now we specify how these vertices are connected together to form the
"faces" of a faceted object. This is provided as a list of faces, each
face specified as a list of vertex indexes that comprise it. The
`Face{N,T,O}` type specifies a face with `N` vertices, with index type
`T` (you should choose `UInt32`), and index-offset `O`. If you're
specifying faces in terms of julia's 1-based indexing, you should set
`O=-1`. (If you instead number the vertices starting with 0, set
`O=0`.)

    ## Provide the list of faces, specified as a 1-based vertex index
    ## This is a simple case: our triangle has only one face
    f = Face{3,UInt32,-1}[(1,2,3)]

	msh = GLNormalMesh(vertices=v, faces=f)

	window = glscreen()

	vis = visualize(msh)
	view(vis, window)

	renderloop(window)

You can rotate the triangle in 3d space by click-drag with the left
mouse button, and translate the triangle by click-drag with the right
mouse button.

## Colorful triangle

?: how to use the `color` field of `HomogeneousMesh`? I tried this:

    msh = GLNormalMesh(vertices=v, faces=f, color=RGBA{U8}(1,0,0,1))
	msh2 = merge(msh)  # sets attributes and attribute_id
	vis = visualize(msh2)
	
but it gave a `MethodError` (for `_default`). I also tried this:

	msh = GLNormalMesh(vertices=v, faces=f)
	vis = visualize(msh, color=fill(RGBA{Float32}(1,0,0,1), 3))

but the triangle wasn't visible.

### CODE REVIEW

**Comment by timholy** [comment]
Also, most of the `compse` examples fail for me with
```jl

ERROR: LoadError: UndefVarError: pango_parse_markup not defined
 in parse_pango at /home/temp/.julia/v0.4/GLVisualize/src/compose_backend.jl:477
 in draw at /home/temp/.julia/v0.4/GLVisualize/src/compose_backend.jl:538
 in draw at /home/temp/.julia/v0.4/GLVisualize/src/compose_backend.jl:377
 in drawpart at /home/temp/.julia/v0.4/Compose/src/container.jl:558
 in drawpart at /home/temp/.julia/v0.4/Compose/src/container.jl:477
 in drawpart at /home/temp/.julia/v0.4/Compose/src/container.jl:590 (repeats 2 times)
 in drawpart at /home/temp/.julia/v0.4/Compose/src/container.jl:477
 in drawpart at /home/temp/.julia/v0.4/Compose/src/container.jl:590 (repeats 2 times)
 in draw at /home/temp/.julia/v0.4/Compose/src/container.jl:434
 in draw at /home/temp/.julia/v0.4/Gadfly/src/Gadfly.jl:822
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
while loading /home/temp/.julia/v0.4/GLVisualize/examples/compose/errorbar.jl, in expression starting on line 20
```

**Comment by SimonDanisch** [comment]
```Julia
Face{N,T,O} type specifies a face with N vertices, with index type
T (you should choose UInt32), and index-offset O. If you're
specifying faces in terms of julia's 1-based indexing, you should set
O=-1. (If you instead number the vertices starting with 0, set
O=0.)
```
This is actually not correct but works for the triangle case, since OpenGL is fault tolerant and basically treats them as circular indexes.
So your face will look to OpenGL (0-indexed) like this: (1,2,0), which also gives you a triangle.
The offset `O` is only used for indexing Julia arrays, while being able to use 0-based indexes. So the offset is relative to julia's one based index, meaning 0 is 1 based and -1 is zero based.... I see how that is confusing ;) I lately wanted to move the indexing behaviour into the integer type, rather than the facetype. When we do this, we might also want to make the parameter more intuitive.

I will add a few tests and examples for creating meshes!

The `pango` stuff is work in progress and not completely working yet.
I added the functions to my Compose fork, but I could also add them to `GLVisualize` instead... That would make it easier to try things out!

The `partice/particle.jl` fix is spot on! 
I'm currently fixing the last bugs and I'm obviously introducing a few new ones while doing so ;)
puzzle

>Does particles/cubicles.jl work for you? I get...

I'm currently working on the camera on `GLAbstraction/sd/camera2`, and haven't merged it yet since it's still not working correctly in all situations... But because of my incredible github workflow, I already added functionality to `GLVisualize/next2` that relies on `GLAbstraction/sd/camera2`

**Comment by timholy** [comment]
> This is actually not correct but works for the triangle case, since OpenGL is fault tolerant and basically treats them as circular indexes.
So your face will look to OpenGL (0-indexed) like this: (1,2,0), which also gives you a triangle.
The offset O is only used for indexing Julia arrays, while being able to use 0-based indexes. So the offset is relative to julia's one based index, meaning 0 is 1 based and -1 is zero based.... I see how that is confusing ;)

Ah, no, it's fine that way too, I just misunderstood.

> I lately wanted to move the indexing behaviour into the integer type, rather than the facetype. When we do this, we might also want to make the parameter more intuitive.

There actually seem to be two options: move it into the integer, or move it into the vertex array. In a sense, I think it's cleanest to say it belongs to the vertex array; you're effectively saying "this array should be indexed with 1-offset (or 0-offset)." One of my crazier ideas is to implement arbitrary indexing for arrays in julia 0.5 (I am not sure if it will happen). But even if the general solution doesn't happen, here you can use a special wrapper, i.e., `ZeroIndexedArray(v)` where `v` is the vertex array. Then other indexes (the faces, the vertex normals, etc) don't have to signal their meaning.

> I'm currently fixing the last bugs and I'm obviously introducing a few new ones while doing so ;)

Don't sweat it, that's a normal even for code that's under such heavy development.

**Comment by timholy** [comment]
> The pango stuff is work in progress and not completely working yet.
I added the functions to my Compose fork, but I could also add them to GLVisualize instead... That would make it easier to try things out!

I'm not exactly sure what it's about, but if it's of general use, would Cairo be the best place to put such things?

**Comment by SimonDanisch** [comment]
>ZeroIndexedArray(v) where v is the vertex array. Then other indexes (the faces, the vertex normals, etc) don't have to signal their meaning.

You often extract faces, pass them around and extract single indexes from a face. I'm not sure how this would play out if this semantic gets moved into the array type.

>I'm not exactly sure what it's about, but if it's of general use, would Cairo be the best place to put such things?

Maybe it's time to create Pango.jl, since neither `Cairo` nor `Compose` seem to be a good place for it ;)

**Comment by timholy** [comment]
> You often extract faces, pass them around and extract single indexes from a face. I'm not sure how this would play out if this semantic gets moved into the array type.

Well, in `Face(i,j,k)`, `i` refers to a particular element in the vertex array. So you can extract the `i` from the face, and it still refers to the same vertex. Then you have two options: `i` could be an `OffsetIndex` and `v` an ordinary array, or `i` could be an `Integer` and `v` could be an `OffsetArray`. Either way, `v[i]` has unambiguous meaning. I suspect it's more straightforward to use the `OffsetArray` solution, in part because you have several "entities" (face indexes, vertex normal indexes, etc) all of which refer to the same vertex array. Having numbers that mean something different than they appear is cool, and we've gotten some great results from using that trick, but it can occasionally be confusing even to people who know the code extremely well (e.g., https://github.com/JeffBezanson/FixedPointNumbers.jl/issues/38).

But it's a good observation that you want to be able to extract the individual indexes and still have them retain their meaning, so either of these solutions will be an improvement over what you have now (which is still quite clever, by the way).

> Maybe it's time to create Pango.jl, since neither Cairo nor Compose seem to be a good place for it ;)

Good idea!

**Comment by SimonDanisch** [comment]
I added one more mesh example, hope that helps you a bit... It also made me realize, that it's not really as neat as I'd like to have it yet. Also I encountered some bugs from `GeometryTypes`, so to try them out you need to checkout the newest commits from `GeometryTypes/sd/boundinbox`

**Comment by timholy** [comment]
Thanks, @SimonDanisch, the recent additions look quite helpful.

I should confess that where I'm headed is volume raycasting with translucent 3d textures. AFAICT this is an area that hasn't received a lot of attention yet, but perhaps I'm missing something. Part of the reason I'm trying to start at the bottom, so I understand how to build new things.

**Comment by SimonDanisch** [comment]
Oh great! If you have any features in mind please tell me! I'd be glad to improve the raycasting, or help you out with it!

I also hope, that the freshly added [FireRender](https://github.com/JuliaGraphics/FireRender.jl) backend will allow some high quality volume ray tracing. (Spoiler alert: It's actually not fully added yet and it seems not to be fully exposed by FireRender yet... But on the website they list Volume rendering) :D

**Pull request merged**
