### PR TITLE
Api test rebuild

### PR DESCRIPTION
**Pull request by SimonDanisch**
@AlainLich @sjkelly, mind trying this out? I tested this on ubuntu and windows on julia's newest master.
It should look something like this (after you moved the camera a bit):
image
There should be some movement and flashing colors^^

You might need to check out WavefrontObj, GLAbstraction and GeometryTypes. I hope there is not more to check out...
I finally added a `runtest` file, so you can just do Pkg.test("GLVisualize").
It's still not an exhaustive test, but it's much better than before ;)
I hope to add all packages to METADA this weekend and then publish a first version.
Next week I want to tackle text editing and widgets.

Best,
Simon

### CODE REVIEW

**Comment by AlainLich** [comment]
Hi Simon

just did, things look promising:
-  git **checkouts**:
```
GLVisualize: upstream/api_test_rebuild
GLAbstraction: upstream/julia04
GeometryTypes.jl:origin/master
```

 - **ADDITIONAL** git **clones** : 
```
cloned  FreeTypeAbstraction.jl 
cloned git@github.com:JuliaIO/WavefrontObj.jl.git
```

At this point I was able to run `runtests.jl`: **nice graphics** !
Tried also my stuff:
1. some tests in Romeo pass (good news)
2. other fail with errors like:
```
ERROR: LoadError: MethodError: `visualize` has no method matching visualize(::Reactive.Lift{Array{GeometryTypes.Point3{Float32},2}}, ::GLAbstraction.Style{:default}, ::Dict{Symbol,Any})
Closest candidates are:
  visualize(!Matched::Reactive.Signal{Array{GeometryTypes.Point2{Float32},1}}, ::GLAbstraction.Style{StyleValue}, ::Any)
  visualize(!Matched::Reactive.Signal{Array{Float32,2}}, ::GLAbstraction.Style{StyleValue}, ::Any)
  visualize{T<:ColorTypes.Color{T,N}}(!Matched::Reactive.Signal{Array{T<:ColorTypes.Color{T,N},2}}, ::GLAbstraction.Style{StyleValue}, ::Any)
  ...
 in visualize at /home/alain/.julia/v0.4/GLVisualize/src/visualize_interface.jl:20 (repeats 2 times)
 in doPlanets at none:202
 in anonymous at no file:249
 in _treeWalkPre! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:260
 in _treeWalkPre! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:271 (repeats 2 times)
 in treeWalk! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:236 (repeats 2 times)
 in init_romeo at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/RomeoLib.jl:302
 in realMain at /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl:127
 in main at /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl:218
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:320
 in _start at ./client.jl:412
while loading /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl, in expression starting on line 221
```
*I will look into this* ( **not tonight though** ...)

**PS**: configuration of Packages related to GLVisualize on my machine:
glvisualize

**Comment by SimonDanisch** [comment]
Great, thanks a lot!
`error: visualize(::Reactive.Lift{Array{GeometryTypes.Point3{Float32},2}}, ::GLAbstraction.Style{:default}, ::Dict{Symbol,Any})`
Yeah this is an API change... I will see how this will turn out, but I put particle in vectors now, not matrices.
Putting them in matrices was just a workaround, because 1D arrays quickly get too large for 1D textures.
We could expose the inner function, which expects a matrix, to the user as well... But I wonder if we should not reserve this for another visualization type. Probably sclices of particles, which all share the same attributes?!
```Julia
[p1 p2  p3 p4 #colored red
p5 p6 p7 p8 #colored green
...]
#Then you  can just pass a second array with the attributes
[rgba(1,0,0,1), #attributes for row 1
rgba(0,1,0,1), #attributes for row 2
...]
# or maybe even a matrix with more than one attribute
[rgba(1,0,0,1) Vec3(0.5); #color + scale
rgba(0,1,0,1) Vec3(2.0);
...]
 ```

Great graphic! Very informative... I hope we can create a git client with such an interface, one of these days ;)

Best,
Simon

**Comment by SimonDanisch** [comment]
(Slices of particles is pretty much what you want for the planets example)

**Comment by AlainLich** [comment]
Hi Simon,

I will check *probably next week* how to get these examples to work again. 

I was wondering which *patterns* ( as defined by en.wikipedia.org/wiki/Design_Patterns http://en.wikipedia.org/wiki/Flyweight_pattern  ) are used by **OGL applications**.  (*Anyway, the
question of how to apply/use patterns in Julia seem of interest*) 

Good Week end

**Comment by SimonDanisch** [comment]
What are you refering to when you say OGL applications? Do you mean the whole stack that GLVisualize uses, or general OGL applications?!

**Comment by AlainLich** [comment]
I was thinking of applications of interest for the end user or the API/Library user. So in this case
it would be GLVisualize (or equivalent in other languages) prospective users.

**Comment by SimonDanisch** [comment]
Well, I explain some stuff in my thesis ;)
https://github.com/SimonDanisch/BachelorThesis/blob/master/BA_sdanisch.pdf
But its not finished yet and if you're only interested in the patterns, there is quite some noise in there ;)

**Comment by AlainLich** [comment]
I guess my remark concern par. 6.3.1 page 39.

**Comment by SimonDanisch** [comment]
Yes, but also 3 and 4.. It's a little spread out, depending on what is more interesting to you..
I like to put in more regarding general design patterns in Julia, but it is simply not in the scope of the thesis :(

**Comment by AlainLich** [comment]
Hi Simon,

I have started looking at differences caused by the **new GLVisualise**. So I am sending issues as they appear. For now, showing an image (jpeg) causes the following:
 -  last message:`Calling visualize arg type=FileIO.File{:jpg}`

 - Then: apparently `visualize` has trouble dealing with this: 

```
ERROR: LoadError: Named attribute (:texturecoordinates) is not an active attribute in the specified program object or

         the name starts with the reserved prefix gl_

 in get_attribute_location at /home/alain/.julia/v0.4/GLAbstraction/src/GLExtendedFunctions.jl:32
 in call at /home/alain/.julia/v0.4/GLAbstraction/src/GLTypes.jl:117
 in call at /home/alain/.julia/v0.4/GLAbstraction/src/GLTypes.jl:155
 in std_renderobject at /home/alain/.julia/v0.4/GLAbstraction/src/GLRenderObject.jl:42 (repeats 2 times)
 in visualize at /home/alain/.julia/v0.4/GLVisualize/src/visualize/image.jl:30
 in visualize at /home/alain/.julia/v0.4/GLVisualize/src/visualize_interface.jl:19
 in visualize at /home/alain/.julia/v0.4/GLVisualize/src/visualize_interface.jl:21 (repeats 2 times)
 in visualizeConduit at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/RomeoLib.jl:138
 in anonymous at no file:255
 in _treeWalkPre! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:260
 in _treeWalkPre! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:271 (repeats 2 times)
 in treeWalk! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:236 (repeats 2 times)
 in init_romeo at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/RomeoLib.jl:302
 in realMain at /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl:127
 in main at /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl:218
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:320
 in _start at ./client.jl:412
while loading /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl, in expression starting on line 221
```

 - Visualize was last called at:
`GLVisualize/src/visualize/image.jl:30`

What do you think?

PS: I have made corrections in the XML parse (and not pushed yet to Romeo/XML), so do not try to reproduce on the version you have.

**Comment by SimonDanisch** [comment]
That's because I have changed something and haven't tested images yet ;)
Its fixed and I'll integrate them into runtest.jl. 
Your error message is odd, though. I thought I improved this. 
With the newest GLAbstraction it should rather say "program 5 not linked" or something like that.

**Comment by AlainLich** [comment]
Hi Simon,
another case I have trouble with  *Signals*; I tried something simpler than the **Planets** example:
```
using GLVisualize, AbstractGPUArray, GLAbstraction, GeometryTypes, Reactive,
      ColorTypes, Meshes, MeshIO

# install a time varying signal
const timer = Input(1)  

function mkCube(p::GeometryTypes.Point3{Float32}, hsz::Float32)
    cube    = GLNormalMesh( Cube( Vec3( p.x, p.y, p.z), Vec3(hsz)))
    GLNormalMesh( cube.vertices, cube.faces)
end

function mkCube(p::GeometryTypes.Point3{Float32}, hsz::Reactive.Signal)
    lift(x -> mkCube( p, Float32(x/10)), hsz)
end

robj1 = visualize([ mkCube(Point3(0.5f0,0.0f0,0.0f0),timer),
          mkCube(Point3(0.0f0,0.5f0,0.0f0),timer)])

map (x -> push!(GLVisualize.ROOT_SCREEN.renderlist, x),  robj1)


@async renderloop() 

while GLVisualize.ROOT_SCREEN.inputs[:open].value
    yield()
    push!(timer, mod1(timer.value+1, 20))
end


```

I get:
```
ERROR: LoadError: There are no defaults for the type Array{Reactive.Lift{MeshIO.HomogenousMesh{GeometryTypes.Point3{Float32},GeometryTypes.Face3{UInt32,-1},GeometryTypes.Normal3{Float32},Void,Void,Void,Void}},1}, 
which either means the implementation is incomplete or not implemented yet.
Consider defining visualize_default(::Array{Reactive.Lift{MeshIO.HomogenousMesh{GeometryTypes.Point3{Float32},GeometryTypes.Face3{UInt32,-1},GeometryTypes.Normal3{Float32},Void,Void,Void,Void}},1}, ::Style, parameters::Dict{Symbol, Any}) => Dict{Symbol, Any} and 
visualize(::Array{Reactive.Lift{MeshIO.HomogenousMesh{GeometryTypes.Point3{Float32},GeometryTypes.Face3{UInt32,-1},GeometryTypes.Normal3{Float32},Void,Void,Void,Void}},1}, ::Style, parameters::Dict{Symbol, Any}) => RenderObject
 in error at error.jl:21
 in visualize_default at /home/alain/.julia/v0.4/GLVisualize/src/visualize_interface.jl:15
 in visualize at /home/alain/.julia/v0.4/GLVisualize/src/visualize_interface.jl:19
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:320
 in _start at ./client.jl:412
while loading /home/alain/src/Julia/Romeo.jl/test/patchSig.jl, in expression starting on line 16
```

**Comment by SimonDanisch** [comment]
Did this really work before!?

2015-06-07 16:09 GMT+02:00 AlainLich <notifications@github.com>:

**Comment by AlainLich** [comment]
Hi,

**no**, this exercise was not needed before, I was  using an `Array{..,2}` in : 
```   
const positions     = lift(send_frame, time_i, Input(world.planets))
const robj          = visualize(positions, model=scalematrix(Vec3(0.1f0)),
                                    screen=sc, camera=cam)
```

now, *as changed to 1D `Array{...,1}`*, I got in trouble with signals and `Point3`. I therefore did a short example (**working**) without Signals:
```
using GLVisualize, AbstractGPUArray, GLAbstraction, GeometryTypes, Reactive,
      ColorTypes, Meshes, MeshIO


function mkCube(p::GeometryTypes.Point3{Float32})
    h =  0.02f0
    cube    = GLNormalMesh( Cube( Vec3( p.x, p.y, p.z), Vec3(h)))
    GLNormalMesh( cube.vertices, cube.faces)
end

robj1 = map ( [ mkCube(Point3(0.5f0,0.0f0,0.0f0)) ,
                mkCube(Point3(0.0f0,0.5f0,0.0f0))] )  do x
                  visualize(x)
              end

map (x -> push!(GLVisualize.ROOT_SCREEN.renderlist, x),  robj1)

renderloop()

```

and then transformed it adding signals, resulting in the non working  chunk I sent.

**Comment by SimonDanisch** [comment]
So you actually need to change the height and width of the cube!?
Going from 2D to 1D should be very simple, as the 2D didn't add any functionality and was just a work around. So if you only have a 2D array, calling vec on it should be enough... In the case of my old examples with nbody, just dropping reshape should suffice.

**Pull request closed without merging**
